theme: jekyll-theme-cayman
title: [Leonardo Fuchs Portfolio]
description: [This website has a brief presentation of my main skills and a portfolio presenting some data science projects that I developed looking to explore machine learning algorithms, also for data analysis, presented in iPython Notebooks.]
